# Generated by Django 4.0.4 on 2022-05-21 08:19

from django.db import migrations, models
import django.db.models.deletion
import timetable.models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonHour',
            fields=[
                ('ID_Lesson_hour', models.BigAutoField(primary_key=True, serialize=False)),
                ('Lesson_no', models.PositiveIntegerField()),
                ('Start_hour', models.PositiveIntegerField()),
                ('Start_minute', models.PositiveIntegerField()),
                ('End_hour', models.PositiveIntegerField()),
                ('End_minute', models.PositiveIntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Break',
        ),
        migrations.RemoveField(
            model_name='lessonsprogram',
            name='FK_Class',
        ),
        migrations.RemoveField(
            model_name='lessonsprogram',
            name='FK_Subject',
        ),
        migrations.AddField(
            model_name='lessonsprogram',
            name='Class',
            field=models.CharField(choices=[('I', 'I'), ('II', 'II'), ('III', 'III'), ('IV', 'IV'), ('V', 'V'), ('VI', 'VI'), ('VII', 'VII'), ('VIII', 'VIII')], default='I', max_length=20),
        ),
        migrations.AddField(
            model_name='lessonsprogram',
            name='Subject',
            field=models.CharField(default='Subject', max_length=20),
        ),
        migrations.AddField(
            model_name='subject',
            name='Color',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='FK_Class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lessons', to='timetable.class'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='Hour',
            field=models.PositiveIntegerField(validators=[timetable.models.validate_hour]),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='Minute',
            field=models.PositiveIntegerField(validators=[timetable.models.validate_minute]),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='Weekday',
            field=models.CharField(choices=[('mon', 'mon'), ('tue', 'tue'), ('wed', 'wed'), ('thu', 'thu'), ('fri', 'fri')], default='mon', max_length=40),
        ),
        migrations.AlterField(
            model_name='lessonsprogram',
            name='Hours_no',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='subject',
            name='Subject_name',
            field=models.CharField(max_length=20),
        ),
        migrations.AddConstraint(
            model_name='lessonhour',
            constraint=models.CheckConstraint(check=models.Q(('Start_hour__lte', 23)), name='Start_hour_check'),
        ),
        migrations.AddConstraint(
            model_name='lessonhour',
            constraint=models.CheckConstraint(check=models.Q(('Start_minute__lte', 59)), name='Start_minute_check'),
        ),
        migrations.AddConstraint(
            model_name='lessonhour',
            constraint=models.CheckConstraint(check=models.Q(('End_hour__lte', 23)), name='End_hour_check'),
        ),
        migrations.AddConstraint(
            model_name='lessonhour',
            constraint=models.CheckConstraint(check=models.Q(('End_minute__lte', 59)), name='End_minute_check'),
        ),
    ]
