# Generated by Django 4.0.4 on 2022-06-01 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher_Subject',
            fields=[
                ('ID_Teacher_Subject', models.BigAutoField(primary_key=True, serialize=False)),
                ('FK_Subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.subject')),
                ('FK_Teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.teacher')),
            ],
        ),
    ]
